name: Build release

on:
  push:
    tags:
      - 'v*'   # Only run when a tag like v1.0, v2.1.3, etc. is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/kpatch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build kpatch binaries
        run: make

      - name: Archive repository
        run: |
          cd $GITHUB_WORKSPACE
          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          zip -r -9 "psfree-lapse-${VERSION}.zip" .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: psfree-lapse-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
